### ISSUE TITLE
Feature Request: Add cli flag for memory formatting

### ISSUE THREAD

**Issue by brocococonut** [skanehira/pst#1]
As the title suggests, I propose a cli flag or argument to change the memory used format from % to number of mb. Sometimes it's not useful to know how much system memory a process is using out of the total, instead it'd be easier to read as a number of mb used. An example format might be:
`pst --memory overall`
The only reason I gave the above example format instead of simply `pst -m` is because you might want to add more formatting options in the future.

**Comment by skanehira** [comment]
@brocococonut Thank you create an issue.
I will implement feature that can change process info format.
I considering interface...

**Comment by skanehira** [comment]
@brocococonut I added `PS_ARG` environment variable, you can use it to change process info.
Please try it :)

**Comment by skanehira** [comment]
@brocococonut I'll close this issue , if you have a some problem please create an issue to let me know :)
